apiVersion: v1
kind: Pod
metadata: 
  labels:
    test: http-liveness
  name: liveness-http-pod
spec:
  containers:
    - name: liveness-http-pod-container
      image: k8s.gcr.io/liveness
      args:
        - /server
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
          httpHeaders: 
            - name: Custom-Header
              value: Awesome
        initialDelaySeconds: 3
        periodSeconds: 3