apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-burstable
  namespace: pods-containers
spec: 
  containers: 
    - name: qos-demo-burstable-ctr
      image: nginx
      resources: 
        limits: 
          memory: "200Mi"
        requests:
          memory: "100Mi"